allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: true # could be expressed as "no-exit: true"
extension:
  - 'js'
reporter: 'spec'
require:
  - 'babel-register'
  - 'tests/helpers'
retries: 1
slow: 5000
spec:
  - 'tests/**/*.js'
  # - 'tests/**/*.spec.js'
watch-files:
  - 'tests/**/*.js'